test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Cloudflare R2
r2:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:r2, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:r2, :secret_access_key) %>
  region: "auto"
  bucket: narratree-production
  endpoint: "https://609d0c7075975cf9ccd00e4ef7c6ee4c.r2.cloudflarestorage.com"
  force_path_style: true
